### ISSUE TITLE
Not Working Auth

### ISSUE THREAD

**Issue by dcmumby** [ZeXtras/zimbra-drive#17]
Hi , I have tried the latest versions of nextcloud 11.05 and 12.03 and the same problem exists. The connection from zimbra (8.7.11) to nextcloud works and I can download files. The login credentials do not work directly on nextcloud neither from webpage nor the sync client.  With local users on both versions of nextcloud the sync and webpage work as expected. Below are the corresponding lines from nextcloud.log and zmmailbox.out

{"reqId":"vMbaZ5z8qEeovZaszeuk","remoteAddr":"xxx.xxx.xxx.xxx","app":"core","message":"Login failed: 'user@domain.com (Remote IP: 'xxx.xxx.xxx.xxx')","level":2,"time":"2017-11-16T10:46:28+00:00","method":"PROPFIND","url":"\/nextcloud\/remote.php\/webdav\/","user":"--","version":"11.0.5.1"}
{"reqId":"vMbaZ5z8qEeovZaszeuk","remoteAddr":"xxx.xxx.xxx.xxx","app":"core","message":"Bruteforce attempt from \"xxx.xxx.xxx.xxx\" detected for action \"login\".","level":1,"time":"2017-11-16T10:46:28+00:00","method":"PROPFIND","url":"\/nextcloud\/remote.php\/webdav\/","user":"--","version":"11.0.5.1"}
{"reqId":"vMbaZ5z8qEeovZaszeuk","remoteAddr":"xxx.xxx.xxx.xxx","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 Username or password was incorrect\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":168,\"User\":false}","level":0,"time":"2017-11-16T10:46:28+00:00","method":"PROPFIND","url":"\/nextcloud\/remote.php\/webdav\/","user":"--","version":"11.0.5.1"}

2017-11-16 12:46:28.034:WARN:oejs.ServletHandler:qtp1068934215-447:https:https://domain.com/service/extension/ZimbraDrive_NcUserZimbraBackend: /service/extension/ZimbraDrive_NcUserZimbraBackend
java.lang.RuntimeException
        at com.zextras.zimbradrive.NcUserZimbraBackendHttpHandler.handleAsAccount(NcUserZimbraBackendHttpHandler.java:108)
        at com.zextras.zimbradrive.NcUserZimbraBackendHttpHandler.doPost(NcUserZimbraBackendHttpHandler.java:59)
        at org.openzal.zal.http.InternalHttpHandler.doPost(InternalHttpHandler.java:57)
        at com.zimbra.cs.extension.ExtensionDispatcherServlet.service(ExtensionDispatcherServlet.java:113)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
        at com.zimbra.cs.servlet.CsrfFilter.doFilter(CsrfFilter.java:169)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:47)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at com.zimbra.cs.servlet.ZimbraInvalidLoginFilter.doFilter(ZimbraInvalidLoginFilter.java:117)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:473)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:318)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:288)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:318)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:437)
        at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:84)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:192)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:748)

this was working correctly with 11.04 before I had a hard drive issue and had to re-install the nextcloud server , I also have a separate system working with same version of zimbra and 11.03 of nextcloud where uploads work without error but are not shown in the nextcloud webpage and likewise files added via the webpage are not shown in the zimbra drive page ?

Please let me know if I can supply any further info

**Comment by Azylog** [comment]
Hello,
I encountered an issue that *seems* to be the same.

Finally, I found that Nextcloud is encoding the username's '@' symbol to %40 in apps/zimbradrive/lib/auth/abstractzimbrausersbackend.php :

At line 224 : 
        return http_build_query($fields);

And this trigger an error in Zimbra drive that checks for the @ sign in the login it receives : 
    if (!username.contains("@"))
    {
      throw new RuntimeException();
    }

So I simply modified abstractzimbrausersbackend.php to : 
        $postfields = http_build_query($fields);
        return urldecode($postfields);

And it works like a charm.

Does this resolve the issue for you too ?

**Comment by dcmumby** [comment]
Hi 

yes this works perfectly , thanx so much for your assistance 



Regards 
Dean Mumby 


----- Original Message -----

**Comment by ybarmax** [comment]
@Azylog hello, i try your solution and show me this message 


Error interno del servidor

El servidor ha encontrado un error y no puede completar la solicitud.

Por favor, contacte con el administrador del servidor si este error reaparece múltiples veces. Incluya asimismo los detalles técnicos que se muestran a continuación.

Pueden verse más detalles en el registro del servidor.

Detalles técnicos

    Dirección remota: 192.168.100.20
    ID de la solicitud: MogQP9Z9OqZbHVCh37d5

**Comment by ZxUgoPadoan** [comment]
The bug should be fixed in the new release (v. 0.8.18), let me know if the problem persists.

**Comment by Azylog** [comment]
Hello,
I can confirm that, issue could be closed.
